 version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-server
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
      - qdrant_config:/qdrant/config
      - ./config.yaml:/qdrant/config/config.yaml:ro
    networks:
      - qdrant-network
    restart: unless-stopped
    command: ./qdrant --config-path /qdrant/config/config.yaml
    environment:
      - QDRANT__LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

volumes:
  qdrant_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/qdrant/data
  qdrant_config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /opt/qdrant/config

networks:
  qdrant-network:
    driver: bridge